# Generated by Django 5.2.4 on 2025-07-23 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_booking'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='hotel_images/')),
                ('rating', models.FloatField()),
                ('reviews', models.IntegerField()),
                ('location', models.CharField(max_length=100)),
                ('discount', models.CharField(max_length=50)),
                ('booking_site', models.CharField(max_length=100)),
                ('offer', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('date_range', models.CharField(max_length=50)),
            ],
        ),
    ]
