# Generated by Django 5.2.4 on 2025-07-29 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_hotel'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='hotel_name',
            field=models.CharField(default='Hotel Unknown', max_length=100),
        ),
    ]
